[package]
name = "git-cc"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.11"
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
